docs/design/template.md

Standardize repository designs.
Fixes https://github.com/migtools/oadp-non-admin/issues/44
Copied template from OADP operator repository https://github.com/openshift/oadp-operator/blob/master/docs/design/_template.md
Read template and see if it is clear about what developers must write.

feat: Add design template

---

internal/common/function/function.go
internal/common/function/function_test.go
internal/controller/nonadminbackup_controller.go

Validate namespaces, so non admin can not create backups outside of ns
Validation ensures the namespace in the VeleroBackup object are the same as the namespace for which NAB resides.
Note this PR is on top of #54 which should be merged first.
1. Setup non-admin user as per instructions: https://github.com/migtools/oadp-non-admin/blob/master/docs/non_admin_user.md
2. Create two NonAdminBackup objects in the namespace for which the non-admin user have namespace admin rights. After each creation see if at the end of reconcile the NonAdminBackup is correctly updated with its status and if in some cases VeleroBackup object was created in the openshift-adp namespace (as an admin) or not created if there was issue with namespace.
All of the below are in the non-admin namespace `nacproject`:
a) …

Validate namespaces, so non admin can not create backups outside of ns

---

api/v1alpha1/nonadminbackup_types.go
config/crd/bases/nac.oadp.openshift.io_nonadminbackups.yaml

This PR adds kubebuilder markers to support Non-Admin backups CR's short name.
***What this means ?***
Earlier to fetch non-admin backups CRs you would execute the command 
`oc get nonadminbackups` 
After this PR, you could use the shortname `nab` instead of the fullname `nonadminbackups` 
***How to test ?***
- Install the non-admin backup CRD from this PR
- Try to execute CRUD commands on nonadminbackups CRD/API endpoint using `nab` shortname instead of full name `nonadminbackups` 
for example:
`oc get nab`

Add kubebuilder markers for resource path and shortname

---

internal/controller/nonadminbackup_controller.go

Fixes issue #65
Whenever we want to exit with error state from the reconcile loop that is considered final state we should use TerminalError.
Returning standard error will cause Reconcile to requeue.
1. Deploy controller without the change
2. Create NonAdminBackup without proper backupSpec, for example
```yaml
apiVersion: nac.oadp.openshift.io/v1alpha1
kind: NonAdminBackup
metadata:
name: example
namespace: nacproject
spec: {}
```
3. Observe controller log. It will show error, however it will re-enter check every few seconds.
With this fix, the point number 3 will not re-enter check every few seconds.
In either scenario proper NonAdminBackup object phase and conditions are correct.

Fix for the Reconcile loop is not exitting properly

---

.github/workflows/ci.yml

Recently, OADP update Go version from 1.20 to 1.22. Our CI is failing because this info is hard coded. This PR automates process of which Go version to use for the OADP job.
Check CI logs. It should not fail as last periodic check https://github.com/migtools/oadp-non-admin/actions/runs/9638007805/job/26578052501

ci: fix OADP Go version

---

.github/workflows/ci.yml
Dockerfile
docs/CONTRIBUTING.md
go.mod

OADP updated Go version to `1.22`. NAC should use same Go version for compatibility.
Changed places found by `grep -Iinr '21' .`
Run project commands and check that everything works as expected.

fix: use Go 1.22

---

.golangci.yml
api/v1alpha1/nonadminbackup_types.go
cmd/main.go
internal/common/function/function.go
internal/common/function/function_test.go
internal/controller/nonadminbackup_controller.go
internal/controller/nonadminbackup_controller_test.go
internal/predicate/composite_predicate.go

Change to remove update of the NAB Spec from the Velero Backup Spec during reconcile loop.
Small nit change to add velerov1 api to import.
Fix #87
- Running `make lint` and `make  test`
- Creating NonAdminBackup object and ensuring only Status will get updated from the original Velero Backup object. The resulting NonAdminBackup object correctly was not updated with the VeleroBackupSpec at the same time Status was updated from the Velero Backup object.

Fix for #87 - Don't update NAB Spec from Velero Backup Spec

---

.github/workflows/ci.yml
docs/CONTRIBUTING.md

We are planning a test day and with CRDs outdated in OADP, it is harder to configure test environment in a cluster.
Fixes #50
Check CI logs, it should enforce that CRDs are up to date.
Also follow [development documentation](https://github.com/mateusoliveira43/oadp-non-admin/blob/fix/crd-check/docs/CONTRIBUTING.md#install-from-source) and check it is working.

fix: Re-enable CRD check

---

internal/common/constant/constant.go
internal/common/function/function.go
internal/common/function/function_test.go
internal/controller/nonadminbackup_controller.go
internal/controller/nonadminbackup_controller_test.go
internal/handler/velerobackup_handler.go
internal/predicate/composite_predicate.go
internal/predicate/nonadminbackup_predicate.go
internal/predicate/velerobackup_predicate.go

As discussed with the team, we want to do less reconcile steps for NAB full reconcile loop (but keeping only making one update call per reconcile). With this PR, NAB reconcile update phases and conditions together in one update call.
Also, simplified Predicate and Handlers logic.
Run tests and check logs (`make simulation-test`) or test in a cluster following [development documentation](https://github.com/migtools/oadp-non-admin/blob/master/docs/CONTRIBUTING.md#install-from-source).

fix: Update NAB status phase and condition together

---

internal/common/function/function.go
internal/common/function/function_test.go
internal/controller/nonadminbackup_controller.go
internal/controller/nonadminbackup_controller_test.go

Fixes #62 
Fixes #60 
Run tests and check logs (`make simulation-test`) or test in a cluster following [development documentation](https://github.com/migtools/oadp-non-admin/blob/master/docs/CONTRIBUTING.md#install-from-source).

fix: Reconcile duplication

---

.github/workflows/ci.yml
Makefile
go.mod

Noticed that CI was not enforcing `go mod tidy` to be run on PRs. Problem was the way the command was being called in Makefile. It needs to be broken into 2 commands to work.
Check CI logs.
[bad run](https://github.com/migtools/oadp-non-admin/actions/runs/11799095918/job/32866808091)
[good run](https://github.com/migtools/oadp-non-admin/actions/runs/11799208873/job/32867178891)

fix: go mod tidy verification

---

cmd/main.go
docs/design/admin_control_over_spec.md
go.mod
go.sum
internal/common/function/function.go
internal/common/function/function_test.go
internal/controller/nonadminrestore_controller.go
internal/controller/nonadminrestore_controller_test.go

Fix #37 
Blocked by https://github.com/openshift/oadp-operator/pull/1600
This PR adds DPA `spec.nonAdmin.enforceRestoreSpec` to `NonAdminRestoreReconciler` and adds validation for NonAdminRestore spec respecting enforcement.
> **Note:** admin user can not enforce falsy values.
Read [design](https://github.com/mateusoliveira43/oadp-non-admin/blob/fix/enforce-restore-spec-field-values/docs/design/admin_control_over_spec.md).
Follow [install-from-source](https://github.com/migtools/oadp-non-admin/blob/master/docs/CONTRIBUTING.md#install-from-source) testing documentation, pointing this branch and my OADP fork branch [`fix/enforce-non-admin-restore-spec-field-values`](https://github.com/mateusoliveira43/oadp-operator/tree/fix/enforce-non-admin-restore-spec-field-values)

fix: Enforce NonAdminRestore spec field values

---

docs/design/admin_control_over_spec.md
go.mod
go.sum

Follow up to fix remaining points from https://github.com/migtools/oadp-non-admin/pull/122
Check CI logs

fix: Follow up fix

---

.golangci.yml

Fix WARNs when running `make lint` command 
On master branch, when running `make lint` command, you should see the following WARNs
```
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. 
WARN [config_reader] The configuration option `run.skip-dirs-use-default` is deprecated, please use `issues.exclude-dirs-use-default`. 
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats` 
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
```
On this branch, you should see no WARNs

fix: lint warns

---

internal/controller/nonadminbackup_controller.go
internal/controller/nonadminrestore_controller.go

Change implementation of the status functions to ensure that an empty status is properly compared against an empty structure, treating it as equivalent to nil
Previous implementation had corner case where reconcile would lead to unnecessary updates, even both statuses were effectively "empty".
To fix reconcile updates to the status where the status should not be updated.
Fix logic observed during controller manual testing.

Non admin status comparison against empty structure

---

api/v1alpha1/nonadmin_types.go
api/v1alpha1/nonadminbackup_types.go
config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
internal/common/constant/constant.go
internal/common/function/function.go
internal/controller/nonadminbackup_controller.go
internal/controller/nonadminbackup_controller_test.go
internal/controller/nonadminrestore_controller.go
internal/handler/velerobackup_queue_handler.go

Change which moves Conditions and Phases into separate nonadmin_types.go that will be used across all other controllers within NonAdmin project. This ensures we are making them part of the API to match them closer to the design.
These changes were introduced to improve the consistency of the NonAdmin project by centralizing the Conditions and Phases. Moving them to a dedicated nonadmin_types.go file provides a single source of truth within API, ensuring that any controller or component working with NonAdminBackup and NonAdminRestore objects can reference these conditions and phases in a consistent way and aligned with design documents and diagrams, ensuring that they are part of the standard data structure shared across the project.
Moving some constants and extracting common strings. …

Move API conditions and phases into common api file

---

api/v1alpha1/nonadminrestore_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/oadp.openshift.io_nonadminrestores.yaml
internal/common/function/function.go
internal/common/function/function_test.go
internal/controller/nonadminrestore_controller.go
internal/controller/nonadminrestore_controller_test.go
internal/handler/velerorestore_queue_handler.go
internal/predicate/compositerestore_predicate.go
internal/predicate/velerorestore_queue_predicate.go

Adds the estimated queue to the NAB restore object
To include estimated queue number for the restore object.
1. Create multiple NAR objects and observe if the queue is proper.
2. Run tests from the source `make simulation-test`
```shell
$ make simulation-test
[...]
Ran 19 of 19 Specs in 23.446 seconds
SUCCESS! -- 19 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestControllers (23.45s)
coverage: 64.6% of statements
```

Implementation for the restore queue

---

.github/workflows/ci.yml

After fixing `make manifests` command in https://github.com/openshift/oadp-operator/pull/1613, CI started to fail because it was reading markers from this repository to generate OADP RBAC.
Check CI logs.

fix: CI fix after make manifests update

---

api/v1alpha1/nonadminbackup_types.go
config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
docs/design/nab_and_nar_status_update.md
internal/controller/nonadminbackup_controller.go
internal/controller/nonadminbackup_controller_test.go

Non Admin Backup delete event should remove corresponding Velero Backup
This allows Velero Sync controller to recreate Velero Backup object and cascate such recreation back to the Non Admin Backup. The cascade action is a responsibility of an Non Admin Sync controller.
Those changes are made to allow sync controller that is implemented as part of the #38 implemented by #138 to recreate Non Admin Backup in unified way, meaning it will be recreated on the new Velero Backup recreation by the Velero Sync controller.
In other words with this behavior when user runs:
```shell
$ oc delete <non-admin-backup> -n mynamespace
```
This will result in removal of associated Velero Backup (if was existing) and then removal of NAB finalizer.
Such action will cause s3 storage to still have the information …

Modify the Non Admin Backup API deletion to align with sync controller

---

internal/common/function/function.go
internal/common/function/function_test.go

Partial implementation for the #146
To restrict default flag from being used for the NaBSL objects.
Run tests
```shell
$ make simulation-tests
```

Restrict NonAdminBSL to set default flag

---

docs/design/non_admin_backupstoragelocation.md
internal/controller/nonadminbackupstoragelocation_controller.go

Fixes #147 
Calls delete on the Non Admin Backup objects referencing Non Admin BSL being removed. The Non Admin Backup controller will propagate the deletion further to remove Velero Backup objects associated with the Non Admin Backups.
Removal of the Non Admin Backup objects after NaBSL removal should happen from the non admin BSL reconcile.
If there are any left-overs GC should take action, so the GC controller should be independent of this logic.
The following delete call will trigger NAB reconcile to propagate this further and remove the Velero Backups
associated with the Non Admin Backup objects being removed.
1. Create NaBSL
2. Associate the Non Admin Backup with the NaBSL
3. Remove the NaBSL
4. Ensure the Non Admin Backup is deleted
5. Ensure the Velero Backup is deleted (this …

Remove associated Non Admin Backups during Non Admin BSL removal

---

Makefile

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>
docker cli will fail to build image without loading image or pushing image
same as https://github.com/kubernetes-sigs/kubebuilder/issues/4546 being fixed in https://github.com/kubernetes-sigs/kubebuilder/pull/4547

feat(Makefile): add docker cli image load support so it can later be pushed

---

internal/common/function/function.go
internal/controller/nonadminbackupstoragelocation_controller.go
internal/controller/nonadminbackupstoragelocation_controller_test.go

Fixes https://github.com/migtools/oadp-non-admin/issues/144
- Try creating a NaBSL object by setting a prefix 
- Try creating a NaBSL object without setting a prefix
- Run unit tests (`make simuation-test`)

Setting NaBSL prefix 

---

internal/common/constant/constant.go
internal/common/function/function.go
internal/common/function/function_test.go
internal/controller/nonadminbackup_controller_test.go

Fixes https://github.com/migtools/oadp-non-admin/issues/200
Fixes https://github.com/migtools/oadp-non-admin/issues/201
Related to https://github.com/openshift/oadp-operator/pull/1632
- Try specifying excludedNamespaces, IncludeClusterResources as true, and non-empty IncludedClusterScopedResources  on NAB backup spec
- NAB should error out

Add validation error on NAB for restricted spec values

---

internal/common/function/function.go
internal/common/function/function_test.go

Fix https://github.com/migtools/oadp-non-admin/issues/202
Check that a NAB can not have volumeSnapshotLocations spec set.

fix: restrict VSL spec in NAB

---

internal/common/constant/constant.go
internal/common/function/function.go
internal/common/function/function_test.go

Fix part of https://github.com/migtools/oadp-non-admin/issues/151
- Try creating NAR with includedNamespaces, ExcludedNamespaces, scheduleName, namespaceMapping
- NAR should error and go to `BackingOff` phase

Add restrictions for non-admin restore spec

---

cmd/main.go
cmd/main_test.go
go.mod
internal/common/constant/constant.go

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>
Fixes #51 
Pairs with https://github.com/openshift/oadp-operator/pull/1635
To enable log level configuration
From https://github.com/openshift/oadp-operator/pull/1635
```
make deploy-olm
```
operator, and override NAC image to `ghcr.io/kaovilai/oadp-non-admin:loglevelConfiguration`
```
❯ docker run --env LOG_LEVEL=1 --env WATCH_NAMESPACE=oadp-operator --rm -it ghcr.io/kaovilai/oadp-non-admin:loglevelConfiguration
2025-02-25T17:32:56Z	INFO	setup	LogLevel: fatal
```
and observe
```
❯ docker run --env LOG_LEVEL=-1 --env WATCH_NAMESPACE=oadp-operator --rm -it ghcr.io/kaovilai/oadp-non-admin:loglevelConfiguration
2025-02-25T17:34:39Z	INFO	setup	LogLevelEnv: -1 is invalid, using default level: info
2025-02-25T17:34:39Z	INFO	setup	LogLevel: …
```

LogLevel configuration via dpa env.

---

api/v1alpha1/nonadminbackup_types.go
config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
internal/controller/nonadminbackup_controller.go
internal/controller/nonadminbackup_controller_test.go
internal/controller/nonadminrestore_controller.go
internal/controller/nonadminrestore_controller_test.go
internal/handler/velerobackup_handler.go
internal/predicate/compositebackup_predicate.go
internal/predicate/velerobackup_predicate.go
internal/predicate/velerorestore_predicate.go

Fix https://github.com/migtools/oadp-non-admin/issues/178
Fix https://github.com/migtools/oadp-non-admin/issues/195
Also add checks to avoid non admin users to maliciously creating NABs that violates NAC rules or using backups from other non admin users.
~Blocked by https://github.com/openshift/oadp-operator/pull/1640~
Follow [install-from-source](https://github.com/migtools/oadp-non-admin/blob/master/docs/CONTRIBUTING.md#install-from-source) testing documentation, pointing this branch and my OADP fork branch [`fix/nac-associated-objects-deletion`](https://github.com/mateusoliveira43/oadp-operator/tree/fix/nac-associated-objects-deletion)
Create NAB, create NAR and then delete associated velero restore. It should be clear in NAR status that its associated velero restore was deleted and …

fix: NonAdmin objects associated objects deletion info

---

internal/common/function/function.go

Fixes #247, which incorrectly showed StorageType
in the BslSpecValidation message when the
objectStorage was enforced by the admin.
To fix #247 
As described in the bug #247 
1. Create enforcements for the NaBSL in the DPA on the objectStorage spec part
2. Create NaBSL that **do not satisfy** enforcements 
3. Check the condition message on the NaBSL object

Fix message for the objectStorage enforcement

---

cmd/main.go
cmd/main_test.go
internal/common/constant/constant.go

Fixes https://issues.redhat.com/browse/OADP-5799
Depends on https://github.com/openshift/oadp-operator/pull/1687
Fixes https://github.com/migtools/oadp-non-admin/issues/254
- Try passing `logFormat` via DPA as `json` or `text`
- Check the NAC deployment/Pod for the value of `LOG_FORMAT` env var
- Finally, check the format of logs in NAC controller pod

OADP-5799:Allow users to set NAC logging to json format

---

Makefile
internal/controller/suite_test.go

Update Kubernetes version used in envtest to match version used by OCP 4.19. Using same setup-envtest version as OADP. Reference https://github.com/openshift/oadp-operator/pull/1682
Check CI logs.

fix: envtest version for OCP 4.19

---

api/v1alpha1/nonadminbackup_types.go
api/v1alpha1/nonadminbackupstoragelocation_types.go
api/v1alpha1/nonadminbackupstoragelocationrequest_types.go
api/v1alpha1/nonadmindownloadrequest_types.go
api/v1alpha1/nonadminrestore_types.go
config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocations.yaml
config/crd/bases/oadp.openshift.io_nonadmindownloadrequests.yaml
config/crd/bases/oadp.openshift.io_nonadminrestores.yaml

Depends-On: https://github.com/openshift/oadp-operator/pull/1709
Implements https://github.com/migtools/oadp-non-admin/issues/232  with additional fields for:
- NonAdminBackup
- NonAdminRestore
- NonAdminBackupStorageLocation
To fix https://github.com/migtools/oadp-non-admin/issues/232 and add similar fields for the NAB and NAR objects.
1. Deployed with local oadp-operator deployment
2. Tested various objects and it's states:
- suspicious-nabsl (reject)
- nonexistingsecretinns-nabsl (do nothing - no nabslrequest)
- waitingapproval-nabsl (do nothing)
- incorrect-bucket-nabsl (approve)
- perfect-nabsl (approve)
```console
$ oc get nabsl -n non-admin-bsl-test
NAME                          REQUEST-APPROVED   REQUEST-PHASE  VELERO-PHASE       AGE
incorrect-bucket-nabsl        False …
```

CRD updates for the oc CLI fields for the NAR, NAB and NABSL objects

---

internal/controller/nonadminbackupstoragelocation_controller.go
internal/handler/nonadminbsl_secret_handler.go
internal/predicate/composite_nabsl_predicate.go
internal/predicate/nonadminbsl_secret_predicate.go

Add reconcile of the NaBSL upon Secret creation in a given namespace
Fixes #212 which reconciles the relevant NaBSL object when the new  Secret is discovered in the user namespace.
Only create events are important, because we do not allow NaBSL updates.
In a handler we compare which NaBSL from the same namespace as secret had the the same credential name as the secret itself and we reconcile on that object. 
To fix #212 
1. Create NaBSL without secret
2. Create secret afterwords in other namespace then the NaBSL (nothing happens)
3. Create secret but with different name in the same namespace as NaBSL (nothing happens) 
4. Create secret that matches the NaBSL credential name (reconcile is fine)
Perform the same steps with enforced name as well perform the same with no credential specified …

Add reconcile of the NaBSL upon Secret creation in a given namespace

---

Dockerfile.oadp

In support of enabling Konflux builds directly from repo.

v1.5: Add downstream Dockerfile
